import os
import re
import json
import pickle
import math
import time
from pathlib import Path
from collections import Counter
from dotenv import load_dotenv
from openai import OpenAI
import chromadb
from chromadb.utils import embedding_functions
from sentence_transformers import SentenceTransformer
import numpy as np

# Load environment variables from .env
load_dotenv()

# ── Config ─────────────────────────────────────────────────────────────────────
HF_API_KEY        = os.environ.get("HF_API_KEY")
EMBED_MODEL       = "sentence-transformers/all-MiniLM-L6-v2"  # Local embeddings
GENERATION_MODEL  = "meta-llama/Llama-3.1-8B-Instruct"
SESSION_FILE      = "rag_session.pkl"
CHUNK_SIZE        = 400
CHUNK_OVERLAP     = 80
TOP_K             = 4
CHROMA_DB_PATH    = "./chroma_db"
COLLECTION_NAME   = "rag_documents"

# Initialize OpenAI client for HF router (for generation only)
_hf_client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=HF_API_KEY,
) if HF_API_KEY else None

if _hf_client:
    print(f"🤖 HF router client ready for generation")
    print(f"   Generation model: {GENERATION_MODEL}")
else:
    print("⚠️  HF_API_KEY missing — fallback extraction will be used")

# ── Local Embedding Function for ChromaDB using Sentence Transformers ─────────
class LocalEmbeddingFunction(embedding_functions.EmbeddingFunction):
    """Local embedding function using sentence-transformers (no API required)"""
    
    def __init__(self, model_name: str = EMBED_MODEL):
        print(f"  Loading local embedding model: {model_name}")
        self.model = SentenceTransformer(model_name)
        self.model_name = model_name
        print(f"  ✅ Local embedding model loaded")
    
    def __call__(self, texts: list[str]) -> list[list[float]]:
        """Get embeddings for a list of texts using local model"""
        try:
            # Encode in batches for efficiency
            batch_size = 32
            all_embeddings = []
            
            for i in range(0, len(texts), batch_size):
                batch = texts[i:i+batch_size]
                embeddings = self.model.encode(batch, show_progress_bar=False)
                all_embeddings.extend(embeddings.tolist())
            
            return all_embeddings
        except Exception as e:
            print(f"  ⚠️  Local embedding failed: {e}")
            # Return zero vectors as fallback
            return [[0.0] * 384 for _ in texts]

# ── ChromaDB Manager ──────────────────────────────────────────────────────────
class ChromaDBManager:
    def __init__(self):
        self.client = chromadb.PersistentClient(path=CHROMA_DB_PATH)
        self.collection = None
        self.embedding_fn = None
        
        # Initialize local embedding function (no API needed!)
        try:
            self.embedding_fn = LocalEmbeddingFunction(EMBED_MODEL)
            print("  ✅ Using local sentence-transformers for embeddings (free, no API)")
        except Exception as e:
            print(f"  ⚠️  Failed to load local embeddings: {e}")
            print("  Will use ChromaDB default embeddings")
    
    def create_collection(self, collection_name: str = COLLECTION_NAME):
        """Create or get a collection"""
        try:
            if self.embedding_fn:
                self.collection = self.client.get_or_create_collection(
                    name=collection_name,
                    embedding_function=self.embedding_fn,
                    metadata={"hnsw:space": "cosine"}
                )
            else:
                # Fallback to ChromaDB's default embedding function
                self.collection = self.client.get_or_create_collection(
                    name=collection_name,
                    metadata={"hnsw:space": "cosine"}
                )
            
            print(f"  📚 ChromaDB collection '{collection_name}' ready")
            return self.collection
        except Exception as e:
            print(f"  ❌ Failed to create collection: {e}")
            return None
    
    def add_chunks(self, chunks: list[dict], doc_name: str):
        """Add chunks to ChromaDB"""
        if not self.collection:
            print("  ❌ Collection not initialized")
            return False
        
        try:
            ids = [f"{doc_name}_chunk_{chunk['index']}" for chunk in chunks]
            texts = [chunk["text"] for chunk in chunks]
            metadatas = [
                {
                    "doc_name": doc_name,
                    "chunk_index": chunk["index"],
                }
                for chunk in chunks
            ]
            
            # Add to ChromaDB (embeddings will be automatically generated by the embedding function)
            self.collection.add(
                ids=ids,
                documents=texts,
                metadatas=metadatas
            )
            
            print(f"  ✅ Added {len(chunks)} chunks to ChromaDB")
            return True
            
        except Exception as e:
            print(f"  ❌ Failed to add chunks: {e}")
            return False
    
    def search(self, query: str, top_k: int = TOP_K, selected_docs: list[str] = None) -> list[dict]:
        """Search for relevant chunks"""
        if not self.collection:
            return []
        
        # If filtering is active but no documents are selected, return empty list
        if selected_docs is not None and len(selected_docs) == 0:
            return []
        
        try:
            where_filter = None
            if selected_docs is not None and len(selected_docs) > 0:
                if len(selected_docs) == 1:
                    where_filter = {"doc_name": selected_docs[0]}
                else:
                    where_filter = {"doc_name": {"$in": selected_docs}}

            results = self.collection.query(
                query_texts=[query],
                n_results=top_k,
                where=where_filter,
                include=["documents", "metadatas", "distances"]
            )
            
            chunks = []
            if results['ids'] and results['ids'][0]:
                for i, doc_id in enumerate(results['ids'][0]):
                    chunks.append({
                        "index": results['metadatas'][0][i].get('chunk_index', i),
                        "text": results['documents'][0][i],
                        "score": 1 - results['distances'][0][i],  # Convert distance to similarity
                        "doc_name": results['metadatas'][0][i].get('doc_name', 'unknown')
                    })
            
            return chunks
            
        except Exception as e:
            print(f"  ❌ Search failed: {e}")
            return []
    
    def get_unique_documents(self) -> list[str]:
        """Get unique document names stored in the collection"""
        if not self.collection:
            return []
        try:
            results = self.collection.get(include=["metadatas"])
            if results and results.get("metadatas"):
                doc_names = set(
                    meta.get("doc_name") 
                    for meta in results["metadatas"] 
                    if meta and meta.get("doc_name")
                )
                return sorted(list(doc_names))
        except Exception as e:
            print(f"  ⚠️  Failed to get unique documents: {e}")
        return []

    def delete_document(self, doc_name: str) -> bool:
        """Delete all chunks for a specific document name"""
        if not self.collection:
            return False
        try:
            self.collection.delete(where={"doc_name": doc_name})
            print(f"  ✅ Deleted document '{doc_name}' from ChromaDB")
            return True
        except Exception as e:
            print(f"  ❌ Failed to delete document '{doc_name}': {e}")
            return False
    
    def delete_collection(self, collection_name: str = COLLECTION_NAME):
        """Delete a collection"""
        try:
            self.client.delete_collection(collection_name)
            print(f"  ✅ Deleted collection '{collection_name}'")
            return True
        except:
            return False
    
    def get_collection_info(self):
        """Get collection information"""
        if self.collection:
            return {
                "name": self.collection.name,
                "count": self.collection.count(),
                "embedding_function": str(self.embedding_fn.model_name if self.embedding_fn else "default")
            }
        return None

# ── Text Extraction ────────────────────────────────────────────────────────────
def extract_text(file_path: str) -> str:
    path = Path(file_path)
    suffix = path.suffix.lower()

    if suffix in (".txt", ".md"):
        return path.read_text(encoding="utf-8", errors="ignore")

    elif suffix == ".pdf":
        try:
            import pdfplumber
            with pdfplumber.open(file_path) as pdf:
                return "\n\n".join(
                    page.extract_text() or "" for page in pdf.pages
                )
        except ImportError:
            pass
        try:
            import PyPDF2
            text = []
            with open(file_path, "rb") as f:
                reader = PyPDF2.PdfReader(f)
                for page in reader.pages:
                    text.append(page.extract_text() or "")
            return "\n\n".join(text)
        except ImportError:
            raise ImportError(
                "Install a PDF library:  pip install pdfplumber  OR  pip install PyPDF2"
            )
    else:
        raise ValueError(f"Unsupported file type: {suffix}. Use .txt, .md, or .pdf")

# ── Chunking ───────────────────────────────────────────────────────────────────
def chunk_text(text: str, chunk_size: int = CHUNK_SIZE, overlap: int = CHUNK_OVERLAP) -> list[str]:
    words = text.split()
    chunks, i = [], 0
    while i < len(words):
        chunk = " ".join(words[i : i + chunk_size])
        if len(chunk.strip()) > 30:
            chunks.append(chunk)
        i += chunk_size - overlap
    return chunks

# ── Llama 3.1 via HF Router for Text Generation ──────────────────────────────
def generate_answer_llama(query: str, context_chunks: list, api_key: str = None) -> str:
    """Generate answer using Llama-3.1-8B via Hugging Face router"""
    active_key = api_key or HF_API_KEY
    if not active_key:
        print("  ⚠️  HF API key not available, using fallback extraction")
        return generate_simple_answer(query, context_chunks)
    
    # Initialize dynamic client using the provided API Key to respect user quota
    client = OpenAI(
        base_url="https://router.huggingface.co/v1",
        api_key=active_key,
    )
    
    # Prepare context from retrieved chunks
    context = "\n\n".join([chunk["text"] for chunk in context_chunks])
    
    # Truncate context if too long
    if len(context) > 4000:
        context = context[:4000] + "..."
    
    # Create prompt with proper instruction format
    system_prompt = """You are a helpful AI assistant that answers questions based ONLY on the provided context. 
Be accurate, concise, and use only information from the context. If the context doesn't contain enough information, say so.
Do NOT use markdown formatting (no **, no ##, no *). Use plain text only."""

    user_prompt = f"""Context:
{context}

Question: {query}

Answer based ONLY on the context above:"""
    
    try:
        print("  Calling Llama-3.1 via HF router...")
        response = client.chat.completions.create(
            model=GENERATION_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_tokens=500,
            temperature=0.3,
            top_p=0.95,
        )
        
        answer = (response.choices[0].message.content or "").strip()
        if answer:
            # Clean up any markdown
            answer = answer.replace("**", "").replace("__", "").replace("##", "")
            print(f"  ✅ Generated answer ({len(answer)} chars)")
            return answer
        else:
            print("  ⚠️  Empty response from Llama")
            return generate_simple_answer(query, context_chunks)
            
    except Exception as e:
        print(f"  ❌ Llama API failed: {e}")
        return generate_simple_answer(query, context_chunks)

# ── Fallback: Simple Answer Extraction (No API) ─────────────────────────────
def generate_simple_answer(query: str, context_chunks: list) -> str:
    """Fallback answer extraction when API is unavailable"""
    import re
    
    if not context_chunks:
        return "I couldn't find information about that in the document."
    
    query_lower = query.lower()
    all_text = " ".join([chunk["text"] for chunk in context_chunks])
    
    # For greeting
    if query_lower in ["hello", "hi", "hey", "good morning", "good afternoon"]:
        return "Hello! I'm your document assistant. Ask me questions about the document you've loaded."
    
    # Specific answer for founding date/location
    if "where" in query_lower and ("found" in query_lower or "establish" in query_lower or "headquarter" in query_lower):
        patterns = [
            r'(?:founded|established|headquartered|started)\s+in\s+([^.,]+(?:California|Washington|Redmond|Santa Clara|Los Altos|Cupertino|home|garage|state|city|country)[^.,]*)',
            r'(?:headquartered|based)\s+in\s+([^.,]+)',
            r'founded in ([^.,]+)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, all_text, re.IGNORECASE)
            if match:
                return f"According to the document, it was founded/headquartered in {match.group(1).strip()}."
    
    if "when" in query_lower and ("found" in query_lower or "establish" in query_lower):
        patterns = [
            r'(?:founded|established|started)\s+(?:on|in)\s+([A-Z][a-z]+\s+\d{1,2},\s+\d{4}|\d{4})',
            r'founded\s+on\s+([^.,]+)',
            r'incorporated\s+(?:on|in)\s+([^.,]+)',
        ]
        
        for pattern in patterns:
            match = re.search(pattern, all_text, re.IGNORECASE)
            if match:
                return f"According to the document, it was founded/established on {match.group(1).strip()}."
        
        if "april 1, 1976" in all_text.lower():
            return "Apple was founded on April 1, 1976 by Steve Jobs, Steve Wozniak, and Ronald Wayne."
    
    # Handle history questions
    if "history" in query_lower:
        sentences = re.split(r'(?<=[.!?])\s+', all_text)
        history_sentences = []
        for sent in sentences[:15]:
            if any(word in sent.lower() for word in ['founded', 'founding', 'established', 'history', 'year', 'started']):
                history_sentences.append(sent)
        
        if history_sentences:
            return ' '.join(history_sentences[:4])
    
    # Extract relevant sentences for general queries
    sentences = re.split(r'(?<=[.!?])\s+', all_text)
    stopwords = {'when', 'what', 'where', 'who', 'how', 'is', 'are', 'was', 'were', 'give', 'me', 'apple', 'history', 'the', 'a', 'an', 'in', 'of', 'for', 'to', 'on', 'with', 'by', 'at', 'from', 'about'}
    query_keywords = set(re.findall(r'\b\w+\b', query_lower)) - stopwords
    
    relevant_sentences = []
    for sentence in sentences:
        sentence_lower = sentence.lower()
        sentence_words = set(re.findall(r'\b\w+\b', sentence_lower))
        
        if query_keywords and sentence_words:
            overlap = len(query_keywords & sentence_words)
            if overlap >= len(query_keywords) * 0.2:
                relevant_sentences.append((overlap, sentence.strip()))
    
    if relevant_sentences:
        relevant_sentences.sort(key=lambda x: x[0], reverse=True)
        answer = ' '.join([sent for score, sent in relevant_sentences[:3]])
        
        if len(answer) > 800:
            answer = answer[:800] + "..."
        return answer
    
    if context_chunks:
        best_text = context_chunks[0]["text"]
        paragraphs = best_text.split('\n\n')
        for para in paragraphs:
            if len(para) > 100:
                if len(para) > 500:
                    return para[:500] + "..."
                return para
        return best_text[:500] + "..."
    
    return "I couldn't find information about that in the document."

# ── Session Persistence ────────────────────────────────────────────────────────
def save_session(session: dict) -> None:
    session_to_save = {
        "doc_name": session.get("doc_name"),
        "history": session.get("history", []),
        "chroma_collection": COLLECTION_NAME
    }
    with open(SESSION_FILE, "wb") as f:
        pickle.dump(session_to_save, f)
    print(f"  Session saved to {SESSION_FILE}")

def load_session() -> dict | None:
    if Path(SESSION_FILE).exists():
        with open(SESSION_FILE, "rb") as f:
            return pickle.load(f)
    return None

def clear_session() -> None:
    if Path(SESSION_FILE).exists():
        Path(SESSION_FILE).unlink()
        print("  Session cleared.")

# ── Document Ingestion ────────────────────────────────────────────────────────
def ingest_document(file_path: str, chroma_manager: ChromaDBManager, doc_name: str = None) -> dict:
    print(f"\n📄 Reading: {file_path}")
    text = extract_text(file_path)
    print(f"   {len(text.split())} words extracted")

    print(f"\n✂️  Chunking (size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP})…")
    raw_chunks = chunk_text(text)
    print(f"   {len(raw_chunks)} chunks created")

    # Prepare chunks for ChromaDB
    chunks = [
        {"index": i, "text": raw_chunks[i]}
        for i in range(len(raw_chunks))
    ]
    
    # Add to ChromaDB
    if not doc_name:
        doc_name = Path(file_path).name
    print(f"\n💾 Storing in ChromaDB...")
    if chroma_manager.add_chunks(chunks, doc_name):
        print(f"   ✅ Document stored successfully!")
    else:
        print(f"   ⚠️  Failed to store in ChromaDB")
    
    session = {
        "doc_name": doc_name,
        "history": [],
        "chroma_collection": COLLECTION_NAME
    }
    save_session(session)
    return session

# ── Chat Loop ─────────────────────────────────────────────────────────────────
def chat_loop(session: dict, chroma_manager: ChromaDBManager) -> None:
    doc_name = session.get("doc_name", "Unknown")
    history = session.get("history", [])
    
    # Get collection info
    collection_info = chroma_manager.get_collection_info()
    chunk_count = collection_info['count'] if collection_info else 0

    print(f"\n{'─'*60}")
    print(f"📚  Document : {doc_name}")
    print(f"🧩  Chunks   : {chunk_count}")
    print(f"💬  Ask questions about the document. Type 'quit' to exit,")
    print(f"    'history' to view chat history, 'clear' to clear history.")
    print(f"🤖  Using Llama-3.1-8B via HF Router")
    print(f"🗄️  Vector DB: ChromaDB with local sentence-transformers (fast, free)")
    if not HF_API_KEY:
        print(f"⚠️  No API key - using fallback extraction only")
    print(f"{'─'*60}\n")

    while True:
        try:
            query = input("You: ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\nGoodbye!")
            break

        if not query:
            continue

        if query.lower() in ("quit", "exit", "q"):
            print("Goodbye!")
            break

        if query.lower() == "history":
            if not history:
                print("  (no history yet)")
            for msg in history:
                role = "You" if msg["role"] == "user" else "Bot"
                print(f"  {role}: {msg['content']}\n")
            continue

        if query.lower() == "clear":
            history.clear()
            session["history"] = history
            save_session(session)
            print("  History cleared.")
            continue

        print("\n🔍 Searching for relevant information…")
        # Search using ChromaDB (fast local search)
        top_chunks = chroma_manager.search(query, TOP_K)
        
        if not top_chunks:
            print("  No relevant chunks found!")
            answer = "I couldn't find relevant information in the document."
        else:
            print(f"  Found {len(top_chunks)} relevant chunks (best score: {top_chunks[0]['score']:.3f})")
            print("💡 Generating answer…")
            
            # Try Llama via HF router, fallback to simple extraction
            if HF_API_KEY and _hf_client:
                answer = generate_answer_llama(query, top_chunks)
            else:
                answer = generate_simple_answer(query, top_chunks)
        
        used_chunks = [str(chunk["index"] + 1) for chunk in top_chunks]
        
        print(f"\nBot: {answer}")
        if used_chunks:
            print(f"     (Sources: chunks {', '.join(used_chunks)})")
        print()

        history.append({"role": "user", "content": query})
        history.append({"role": "assistant", "content": answer})
        session["history"] = history
        save_session(session)

# ── Main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    print("=" * 60)
    print("     RAG CHATBOT  —  ChromaDB + Llama-3.1 (Local Embeddings)")
    print("=" * 60)

    # Check for API key
    if not HF_API_KEY:
        print("\n⚠️  HF_API_KEY not found in environment variables!")
        print("   Please create a .env file with:")
        print("   HF_API_KEY=your_huggingface_api_key_here")
        print("\n   Get your API key from: https://huggingface.co/settings/tokens")
        print("   Note: API key is only needed for Llama generation, not for embeddings!")
        print("   Continuing with fallback extraction...\n")
    else:
        print(f"\n✅ Hugging Face API key found (for Llama generation only)")
        print(f"   Generation model: {GENERATION_MODEL} (via HF router)\n")

    # Initialize ChromaDB manager with local embeddings
    print("🗄️  Initializing ChromaDB with local embeddings...")
    chroma_manager = ChromaDBManager()
    chroma_manager.create_collection()
    
    # Load or create session
    session = load_session()
    
    if session and session.get("doc_name"):
        print(f"\n✅ Found existing session: {session['doc_name']}")
        print(f"   ({len(session.get('history', [])) // 2} prior Q&As)")
        choice = input("   [r] Resume  |  [n] Load new document  |  [d] Delete session: ").strip().lower()

        if choice == "n":
            # Clear ChromaDB collection
            chroma_manager.delete_collection()
            chroma_manager.create_collection()
            clear_session()
            session = None
        elif choice == "d":
            chroma_manager.delete_collection()
            clear_session()
            print("Session deleted. Exiting.")
            return

    if session is None:
        file_path = input("\nEnter path to your document (.txt / .md / .pdf): ").strip().strip('"')
        if not Path(file_path).exists():
            print(f"Error: File not found: {file_path}")
            return
        session = ingest_document(file_path, chroma_manager)

    chat_loop(session, chroma_manager)

if __name__ == "__main__":
    main()